// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsO3KRv-cWcpZbAif6PRohlinm72m5BQI',
    appId: '1:107316073750:web:f257e4fc5863011608ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    authDomain: 'metrotaxi-782a6.firebaseapp.com',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    measurementId: 'G-F6SBWFVXZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrHaw5OtXLfChnPf8A6QHFbPyp76WjtYo',
    appId: '1:394465491097:android:a60538658d1460b1e1a008',
    messagingSenderId: '394465491097',
    projectId: 'metroberry-cbbd8',
    storageBucket: 'metroberry-cbbd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCVu12VO7_NBTkyVdnE14r381kHDzYZKI',
    appId: '1:394465491097:ios:37731d3b8e2d3f9ce1a008',
    messagingSenderId: '394465491097',
    projectId: 'metroberry-cbbd8',
    storageBucket: 'metroberry-cbbd8.appspot.com',
    androidClientId: '394465491097-5gkt7agea88d12t83d53v8ki3liilqhq.apps.googleusercontent.com',
    iosClientId: '394465491097-j29k3gvidnlcio3t04sneobhbs6rtrr5.apps.googleusercontent.com',
    iosBundleId: 'com.mytaxi.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMCKDNnORaG3lfyhF0l04KI3MmyAqLHg',
    appId: '1:107316073750:ios:7c9180e14998782208ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    androidClientId: '107316073750-fnou107ufc1v6vambv9b6khu5fbdub4e.apps.googleusercontent.com',
    iosClientId: '107316073750-5h6fbu1g13ve2755kdge6v5rgak8uhd8.apps.googleusercontent.com',
    iosBundleId: 'com.admin.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsO3KRv-cWcpZbAif6PRohlinm72m5BQI',
    appId: '1:107316073750:web:e0a4ac614d718ec108ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    authDomain: 'metrotaxi-782a6.firebaseapp.com',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    measurementId: 'G-DFMWBKQ5N1',
  );

}