// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4aOxLRrvhTVBmdmMy4ZZawtzKPAtdG3Q',
    appId: '1:394465491097:web:19a098cd60e9647fe1a008',
    messagingSenderId: '394465491097',
    projectId: 'metroberry-cbbd8',
    authDomain: 'metroberry-cbbd8.firebaseapp.com',
    storageBucket: 'metroberry-cbbd8.appspot.com',
    measurementId: 'G-28ZV47GM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrHaw5OtXLfChnPf8A6QHFbPyp76WjtYo',
    appId: '1:394465491097:android:a60538658d1460b1e1a008',
    messagingSenderId: '394465491097',
    projectId: 'metroberry-cbbd8',
    storageBucket: 'metroberry-cbbd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCVu12VO7_NBTkyVdnE14r381kHDzYZKI',
    appId: '1:394465491097:ios:37731d3b8e2d3f9ce1a008',
    messagingSenderId: '394465491097',
    projectId: 'metroberry-cbbd8',
    storageBucket: 'metroberry-cbbd8.appspot.com',
    androidClientId: '394465491097-5gkt7agea88d12t83d53v8ki3liilqhq.apps.googleusercontent.com',
    iosClientId: '394465491097-j29k3gvidnlcio3t04sneobhbs6rtrr5.apps.googleusercontent.com',
    iosBundleId: 'com.mytaxi.admin',
  );

}