// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBogR4oMz-TOcTLb3UOSFnosIcJeNf8GMY',
    appId: '1:516978414394:web:29c25801dbbc942405b603',
    messagingSenderId: '516978414394',
    projectId: 'metroberrytaxi',
    authDomain: 'metroberrytaxi.firebaseapp.com',
    storageBucket: 'metroberrytaxi.appspot.com',
    measurementId: 'G-HQ6T4V9JFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-rjlGJmeA1M_qZGrNvI_kzPPgxYci-4',
    appId: '1:516978414394:android:700d4324cce625e105b603',
    messagingSenderId: '516978414394',
    projectId: 'metroberrytaxi',
    storageBucket: 'metroberrytaxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8kY_B6vSjrY0mFWgDxlmZKs00oUvpi0Q',
    appId: '1:516978414394:ios:e67239a96936e0a905b603',
    messagingSenderId: '516978414394',
    projectId: 'metroberrytaxi',
    storageBucket: 'metroberrytaxi.appspot.com',
    androidClientId: '516978414394-qu56goc013h5kmpbojt42475no3nbrno.apps.googleusercontent.com',
    iosClientId: '516978414394-nk2ka5pdoa5me1kcg8scplt4bolcgfsl.apps.googleusercontent.com',
    iosBundleId: 'com.mytaxi.admin',
  );

}